class_name ServerHeaders extends RefCounted

enum Headers {
	PING,
	ALERT,
	NOTIFICATION,
	ACCESS_ACCOUNT,
	CREATE_ACCOUNT,
	DELETE_ACCOUNT,
	RECOVER_ACCOUNT,
	CHANGE_PASSWORD,
	CHARACTER_LIST,
	CREATE_CHARACTER,
	DELETE_CHARACTER,
	SELECT_CHARACTER,
	WORLD_CHARACTERS_TO,
	NEW_CHARACTER_TO,
	MOVE_CHARACTER_TO_OTHERS,
	BLOCK_CHARACTER_MOVEMENT,
	DISCONNECT_CHARACTER,
	TELEPORT_CHARACTER,
	CHAT_MESSAGE,
	EMOTE_MESSAGE,
}
