class_name ClientHeaders extends RefCounted


enum Headers {
	PING,
	ACCESS_ACCOUNT,
	CREATE_ACCOUNT,
	DELETE_ACCOUNT,
	RECOVER_ACCOUNT,
	CHANGE_PASSWORD,
	CHARACTER_LIST,
	CREATE_CHARACTER,
	DELETE_CHARACTER,
	SELECT_CHARACTER,
	MOVE_CHARACTER,
	TELEPORT_CHARACTER,
	CHAT_MESSAGE,
	EMOTE_MESSAGE,
	CHARACTER_DATA,
}
